### ISSUE TITLE
clip() using lines or boxes does not return an output

### ISSUE THREAD

**Issue by KCanner** [cormullion/Luxor.jl#289]
I want to clip using lines and arcs, but when I clip using lines nothing is returned.  
This also seems to also be an issue when using box() but functions correctly using circle()

@draw begin
    line(Point(100,0),Point(0,100))
    line(Point(0,100),Point(-100,0))
    line(Point(-100,0),Point(0,-100))
    line(Point(0,-100),Point(100,0))
    clip()
    circle(O, 90, :fill)
end

**Comment by cormullion** [comment]
Hi!

A good way to see what's going on is to use `fillpath()` or `storepath()` rather than `clip()` to see the path before using it for clipping.

What you've made with your code is a path with four separate subpaths each with a single line, rather than a path with one subpath with four lines.

```julia
Path([
 PathMove(Point(100.0, 0.0)),
 PathLine(Point(0.0, 100.0)),
 PathMove(Point(0.0, 100.0)),
 PathLine(Point(-100.0, 0.0)),
 PathMove(Point(-100.0, 0.0)),
 PathLine(Point(0.0, -100.0)),
 PathMove(Point(0.0, -100.0)),
 PathLine(Point(100.0, 0.0))
])
```

and single line segments, whether on their own or stored in a sequence, can't do clipping.

What you probably want is:

```Julia
    move(Point(100, 0))
    line(Point(0, 100)) 
    line(Point(-100, 0))
    line(Point(0, -100))
    closepath()

    clip()
```

which creates a single path with one subpath with four line segments.
